- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Update cache
    apt:
      update_cache: yes

  - name: Install essential packages
    apt:
      pkg:
      - vim
      - curl
      - htop
      - git

