- hosts: all
  tasks:

  - name: Remove old global config
    file:
      path: '{{ item }}'
      state: absent
    with_items:
    - '/usr/local/share/.oh-my-zsh'

  - name: Uninstall VSC
    apt:
      pkg: code
      state: absent

  - name: Uninstall VLC
    apt:
      pkg: vlc
      state: absent

  - name: Uninstall fish
    apt:
      pkg: fish
      state: absent

  - name: Uninstall pinta
    apt:
      pkg: pinta
      state: absent
