- hosts: all
  become: yes
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  - name: Check version
    import_tasks: tasks/version.yml
  tasks:
  - name: Install basic enviroment
    import_tasks: tasks/basic_enviroment.yml
  - name: Create mc config
    file:
      path: '/home/{{ username.stdout }}/.config/mc'
      state: directory
    become: yes
    become_user: '{{ username.stdout }}'
  - name: Copy mc settings
    copy:
      src: './res/mc-ini'
      dest: '/home/{{ username.stdout }}/.config/mc/ini'
    become: yes
    become_user: '{{ username.stdout }}'
  - name: Install and configure shell and prompt
    import_tasks: tasks/terminal.yml
  - name: Install bashcfg
    import_tasks: tasks/bashcfg.yml
  - name: Install vimrc
    import_tasks: tasks/vimrc.yml
