- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: Install dependencies
    apt:
      pkg:
      - zsh
      - curl
      - git

 # Checks
 
  - name: Check if ~/.oh-my-zsh exists
    stat:
      path: '{{ ansible_env.HOME }}/.oh-my-zsh'
    register: ohmyzsh

  - name: Check if /usr/local/share/.oh-my-zsh exists
    stat:
      path: '/usr/local/share/.oh-my-zsh'
    register: ohmyzsh_share
 
  - name: Check if /usr/local/share/.oh-my-zsh/themes/babun.zsh-theme exists
    stat:
      path: '/usr/local/share/.oh-my-zsh/themes/babun.zsh-theme'
    register: theme 
 
  - name: Check if ~/zshrc exists
    stat:
      path: '{{ ansible_env.HOME }}/.zshrc'
    register: zshrc

 # Commands

  - name: Set ZSH as default shell
    user:
      name: '{{ ansible_user_id }}'
      shell: /bin/zsh

  - name: Install oh-my-zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    when:
    - not ohmyzsh.stat.exists
    - not ohmyzsh_share.stat.exists

  - name: remove default config
    file:
      path: '{{ ansible_env.HOME }}/.zshrc'
      state: absent

  - name: Clone zshrc repo
    git:
     repo: 'https://github.com/InternetGuru/zshrc'
     dest: '{{ ansible_env.HOME }}/zshrc'
  
  - name: Move .oh-my-zsh to /usr/local/share
    shell: mv '{{ ansible_env.HOME }}/.oh-my-zsh' /usr/local/share
    when: not ohmyzsh_share.stat.exists

  - name: Add babun.zsh-theme into oh-my-zsh
    file:
      src: '{{ ansible_env.HOME }}/zshrc/babun.zsh-theme'
      dest: '/usr/local/share/.oh-my-zsh/themes/babun.zsh-theme'
      state: link
    when: not theme.stat.exists

  - name: Set .zshrc
    file:
      src: '{{ ansible_env.HOME }}/zshrc/.zshrc'
      dest: '{{ ansible_env.HOME }}/.zshrc'
      state: link
    when: not zshrc.stat.exists

  - name: Add syntax higlight
    git:
      repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
      dest: '/usr/local/share/.oh-my-zsh/plugins/zsh-syntax-highlighting'


