- hosts: all
  pre_tasks:
  - name: Check version
    import_tasks: tasks/version.yml
    tags:
      - user
      - global
  vars:
    swap_file_size_mb: '2048'
    swap_file_path: '/root/swapfile'
  roles:
    - role: geerlingguy.swap
      tags:
        - global
  tasks:
  - name: Install motd
    import_tasks: tasks/motd.yml
    tags: global
  - name: Set firewall
    import_tasks: tasks/ufw.yml
    tags: global
