- hosts: all
  become: yes
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  roles:
  - avnes.ansible-role-slack
  - geerlingguy.java
  tasks:
  - name: Install virtualbox
    apt:
      name: virtualbox
      update_cache: yes
  - name: Install docker
    import_tasks: tasks/docker.yml
  - name: Install PHP
    import_tasks: tasks/php.yml
  - name: Install omgf
    import_tasks: tasks/omgf.yml
  - name: Install butt
    import_tasks: tasks/butt.yml
