- hosts: all
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  - name: Check version
    import_tasks: tasks/version.yml
    tags:
      - user
      - global
  roles:
  - role: geerlingguy.java
    tags: global
  tasks:
  - name: Install slack
    snap:
      name: slack
      classic: yes
    tags: global
  - name: Install discord
    snap:
      name: discord
      classic: yes
    tags: global
  - name: Install virtualbox
    apt:
      name: virtualbox
    tags: global
  - name: Install sublime
    import_tasks: tasks/sublime.yml
  - name: Install docker
    import_tasks: tasks/docker.yml
    tags: global
  - name: Install PHP
    import_tasks: tasks/php.yml
    tags: global
  - name: Install omgf
    import_tasks: tasks/omgf.yml
    tags: global
  - name: Install butt
    import_tasks: tasks/butt.yml
    tags: global
  - name: Install diff-so-fancy
    import_tasks: tasks/diff-so-fancy.yml
  - name: Create workspace
    import_tasks: tasks/work.yml
    tags: user
