- hosts: all
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  - name: Check version
    import_tasks: tasks/version.yml
  roles:
  - role: avnes.ansible-role-slack
    tags:
      - global
  - role: geerlingguy.java
    tags:
      - global
  tasks:
  - name: Install virtualbox
    apt:
      name: virtualbox
      update_cache: yes
    tags:
      - global
  - name: Install sublime
    import_tasks: tasks/sublime.yml
  - name: Install docker
    import_tasks: tasks/docker.yml
  - name: Install PHP
    import_tasks: tasks/php.yml
  - name: Install omgf
    import_tasks: tasks/omgf.yml
  - name: Install butt
    import_tasks: tasks/butt.yml
