- hosts: all
  become: yes
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  roles:
  - cmprescott.chrome
  - role: PeterMosmans.customize-gnome
    vars:
      gnome_user: '{{ username.stdout }}'
      gnome_extensions:
        - url: https://extensions.gnome.org/extension-data/disable-screenshield%40lgpasquale.com.v7.shell-extension.zip
          name: 'disable-screenshield@lgpasquale.com'
        - url: https://extensions.gnome.org/extension-data/clock-overridegnomeshell.kryogenix.org.v12.shell-extension.zip
          name: 'clock-override@gnomeshell.kryogenix.org'
  tasks:
  - name: Set default browser
    shell: xdg-settings set default-web-browser google-chrome.desktop
  - name: Install packages
    apt:
      pkg:
      - gnome-screensaver 
      - gnome-session
      - gnome-settings-daemon
      - gnome-tweaks
      - gnome-shell-extension-dash-to-panel
      - python3-pip
      - pinta
      - rtorrent
      - rhythmbox
      - vlc
  - name: Install we-get
    pip:
      name:
      - prompt_toolkit==1.0.14
      - git+https://github.com/rachmadaniHaryono/we-get
  - name: Clone settings
    git: 
      repo: 'https://github.com/jiripavelka/ubuntucfg.git'
      dest: '/home/{{ username.stdout }}/ubuntucfg'
  - name: Change ownership
    file:
      path: '/home/{{ username.stdout }}/ubuntucfg'
      owner: '{{ username.stdout }}'
      group: '{{ username.stdout }}'
      state: directory
      recurse: yes
  - name: Show lang switch
    command: gsettings set org.gnome.desktop.input-sources show-all-sources true
  - name: Add Ulauncher APT repository
    apt_repository:
      repo: 'ppa:agornostal/ulauncher'
  - name: Install Ulauncher
    apt:
      pkg:
      - ulauncher
      update_cache: yes
  - name: Set lid close behaviour to ignore
    shell: sed -i 's/^HandleLidSwitch.*/HandleLidSwitch=ignore/' /etc/systemd/logind.conf
  - name: crate ~/.ssh to suppress ssh-agent warning
    file:
      path: /home/{{ username.stdout }}/.ssh
      owner: '{{ username.stdout }}'
      group: '{{ username.stdout }}'
      state: directory
  - name: Install zoom
    apt:
      deb: https://zoom.us/client/latest/zoom_amd64.deb
    ignore_errors: yes
  - name: Load ubuntu settings
    import_tasks: tasks/ubuntucfg.yml
