- hosts: all
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  - name: Check version
    import_tasks: tasks/version.yml
    tags:
      - user
      - global
  roles:
  - role: avnes.ansible-role-slack
    tags: global
  - role: geerlingguy.java
    tags: global
  tasks:
  - name: Install virtualbox
    apt:
      name: virtualbox
      update_cache: yes
    tags: global
  - name: Install sublime
    import_tasks: tasks/sublime.yml
  - name: Install docker
    import_tasks: tasks/docker.yml
    tags: global
  - name: Install PHP
    import_tasks: tasks/php.yml
    tags: global
  - name: Install omgf
    import_tasks: tasks/omgf.yml
    tags: global
  - name: Install butt
    import_tasks: tasks/butt.yml
    tags: global
  - name: Create workspace
    shell: "bash -c '[[ ! -d /home/{{ username.stdout }}/work ]] && mkdir /home/{{ username.stdout }}/work && touch /home/{{ username.stdout }}/work/{bash.sh,email.html,java.java,latex.tex,php.php,text.txt,data.dat,email.md,json.json,markdown.md,python.py,sample.bib,yaml.yml} && chmod +x /home/{{ username.stdout }}/work/bash.sh'"
    tags: user