- hosts: all
  pre_tasks:
  - name: Register current user name
    import_tasks: tasks/user_name.yml
  - name: Check version
    import_tasks: tasks/version.yml
    tags:
      - user
      - global
  roles:
  - role: cmprescott.chrome
    tags:
      - global
  - role: PeterMosmans.customize-gnome
    vars:
      gnome_user: '{{ username.stdout }}'
      gnome_extensions:
        - url: https://extensions.gnome.org/extension-data/disable-screenshield%40lgpasquale.com.v7.shell-extension.zip
          name: 'disable-screenshield@lgpasquale.com'
        - url: https://extensions.gnome.org/extension-data/clock-overridegnomeshell.kryogenix.org.v12.shell-extension.zip
          name: 'clock-override@gnomeshell.kryogenix.org'
    tags:
      - global
  tasks:
  - name: Set default browser
    shell: xdg-settings set default-web-browser google-chrome.desktop
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      - user
  - name: Create ~/.config/google-chrome/
    file:
      path: '/home/{{ username.stdout }}/.config/google-chrome/'
      state: directory
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      - user
  - name: Touch google-chrome first run file
    file:
      path: '/home/{{ username.stdout }}/.config/google-chrome/First Run'
      state: touch
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      - user
  - name: Install packages
    apt:
      pkg:
      - gnome-screensaver
      - gnome-session
      - gnome-settings-daemon
      - gnome-tweaks
      - gnome-shell-extension-dash-to-panel
      - python3-pip
      - pinta
      - rtorrent
      - rhythmbox
      - mpv
      - wmctrl
      - variety
      update_cache: yes
    tags:
      - global
  - name: Symbolic link pip3 to pip
    file:
      src: '/usr/bin/pip3'
      dest: '/usr/bin/pip'
      state: link
    tags:
      - global
  - name: Symbolic link python3 to python
    file:
      src: '/usr/bin/python3'
      dest: '/usr/bin/python'
      state: link
    tags:
      - global
  - name: Install we-get and psutil
    pip:
      name:
      - prompt_toolkit==1.0.14
      - git+https://github.com/rachmadaniHaryono/we-get
      - psutil
    tags:
      - global
  - name: Install google remote desktop
    apt:
      deb: https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
    tags:
      - global
  - name: Set lid close behavior to ignore
    lineinfile:
      path: /etc/systemd/logind.conf
      regexp: '^HandleLidSwitch='
      line: HandleLidSwitch=ignore
    tags:
      - global
  - name: Install zoom
    apt:
      deb: https://zoom.us/client/latest/zoom_amd64.deb
    ignore_errors: yes
    tags:
      - global
  - name: Install night-light control script
    copy:
      src: './res/night-light'
      dest: '/usr/local/bin/'
      mode: '0777'
    tags:
      - global
  - name: Load ubuntu settings
    import_tasks: tasks/ubuntucfg.yml
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      user
  - name: Load ubuntu shortcuts
    import_tasks: tasks/ubuntukeys.yml
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      user
  - name: Auto install drivers
    shell: 'ubuntu-drivers autoinstall'
    tags:
      - global
  - name: Create link to current ansible readme
    import_tasks: tasks/ansible_info.yml
    tags:
      - user
  - name: Install variety
    import_tasks: tasks/variety.yml
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
      - user

