#!/bin/bash

rootPwd="$1"
version="$(<$rootPwd/VERSION)-$(git -C "$rootPwd" rev-parse --abbrev-ref HEAD)"
readme="$(sed -n '/^## Default Shortcuts/,/^## Suggestions/p' "$rootPwd/README.md" \
  | grep -v "^## Suggestions" \
  | sed 's/^## \(.*\)/<big><b>\1<\/b><\/big>/g')"

printf "$(< "$rootPwd/res/.ansible-info")" "$version" "$rootPwd" "$readme" > "/home/$2/.ansible-info"
