#!/bin/bash

home="/home/$(id -un)"

[[ -f "$home/.ansible-info-hide" ]] \
  && exit

user-dialog --question "$(</home/$(id -un)/.ansible-info)\n\n<big><b>Show again on next startup?</b></big>" \
  || touch "$home/.ansible-info-hide"
