#!/bin/bash

text="$(</dev/stdin)"
[[ -n "$2" ]] \
  && text="$text\n\n<big><b>$2</b></big>"
   
zenity \
--text="$text" \
--"${1:-info}" \
--title="Internet Guru Ubuntu Ansible" \
--icon-name "starred" \
--width="700"
