#!/bin/bash

commit="$(git -C "$1" rev-parse HEAD)"
dest="/usr/local/share/ansible-info"

printf "%s\n%s\n" \
  "#!/bin/bash" \
  "google-chrome --app=\"https://github.com/InternetGuru/ansible/blob/$commit/README.md\"" \
  > "$dest"

chmod +x "$dest"
