#!/bin/bash

home="/home/$(id -un)"

[[ -f "$home/.ansible-info-hide" ]] \
  && exit

ansible-user-dialog question "Show again on next startup?" </home/"$(id -un)"/.ansible-info \
  || touch "$home/.ansible-info-hide"
