
 # Dependency

 # Checks

 # Commands

  - name: Generate ansible-info file
    shell: '{{ playbook_dir }}/res/ansible-info-generate "{{ playbook_dir }}" "{{ username.stdout }}"'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Create ansible-info link to Desktop
    file:
      src: '/home/{{ username.stdout }}/ansible-info'
      dest: '/home/{{ username.stdout }}/Desktop/ansible-info'
      state: link
      force: yes
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Run info script on startup
    copy:
      src: '../res/ansible-startup'
      dest: '/etc/init.d/'
      mode: '0777'

