
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - zenity

 # Checks

 # Commands

  - name: Generate .ansible-info file
    shell: '../res/ansible-info-generate "{{ playbook_dir }}" "{{ username.stdout }}"'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Run info script on startup
    copy:
      src: '../res/ansible-startup'
      dest: '/etc/init.d/'
