
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - zenity

 # Checks

 # Commands

  - name: Generate .ansible-info file
    shell: 'printf "$(< "../res/.ansible-info")" "$(<../VERSION)-$(git -C .. rev-parse --abbrev-ref HEAD)" "{{ playbook_dir }}" "$(../res/ansible-info-parse) \"{{ playbook_dir }}/README.md\"" > /home/{{ username.stdout }}/.ansible-info'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Run info script on startup
    copy:
      src: '../res/ansible-startup'
      dest: '/etc/init.d/'
