 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
    tags: global

 # Checks

  - name: Check if IG bashcfg is already in bashrc
    lineinfile:
      state: absent
      path: '/home/{{ username.stdout }}/.bashrc'
      regexp: '^echo "Internet Guru config'
    check_mode: true
    changed_when: false
    register: checkigcfgbash
    tags: user

 # Commands

  - name: Add settings into bashrc
    shell: 'echo "{{ item }}" >> /home/{{ username.stdout }}/.bashrc'
    changed_when: False
    with_items:
    - 'echo \"Internet Guru config, version $(< /usr/local/share/bashcfg/VERSION)\"'
    - 'source /usr/local/share/bashcfg/common'
    - 'source /usr/local/share/bashcfg/git_functions'
    when: checkigcfgbash.found == 0
    become: yes
    become_user: '{{ username.stdout }}'
    tags: user
