
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
    tags:
    - global

 # Checks

  - name: Check if IG bashcfg is already in config.fish
    lineinfile:
      state: absent
      path: '/home/{{ username.stdout }}/.config/fish/config.fish'
      regexp: '^echo "Internet Guru config'
    check_mode: true
    changed_when: false
    register: checkigcfg
    tags:
    - user

 # Commands

  - name: Clone bashcfg
    git:
     repo: 'https://bitbucket.org/igwr/bashcfg'
     dest: '/usr/local/share/bashcfg'
    tags:
    - user
    - global

  - name: Add settings into config.fish
    shell: 'echo "{{ item }}" >> /home/{{ username.stdout }}/.config/fish/config.fish'
    changed_when: False
    with_items:
    - 'echo \"Internet Guru config, version \"(cat /usr/local/share/bashcfg/VERSION)'
    - 'source /usr/local/share/bashcfg/common.fish'
    - 'source /usr/local/share/bashcfg/git_functions.fish'
    when: checkigcfg.found == 0
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
    - user
