 
 # Dependency
 
  - name: Install dependencies
    apt:
      pkg:
      - git

 # Checks
 
  - name: Check if /usr/local/share/bashcfg exists
    stat:
      path: '/usr/local/share/bashcfg'
    register: bashcfg

  - name: Check if ~/.zshrc.local exists
    stat:
      path: '/home/{{ username.stdout }}/.zshrc.local'
    register: zshrclocal

 # Commands

  - name: Clone bashcfg
    git:
     repo: 'https://bitbucket.org/igwr/bashcfg'
     dest: '/usr/local/share/bashcfg'

  - name: Add settings into .zshrc.local
    shell: '{{ item }}'
    changed_when: False
    with_items:
    - "echo 'echo \"IG bashcfg, version $(< /usr/local/share/bashcfg/VERSION)\"' >> /home/{{ username.stdout }}/.zshrc.local"
    - "echo 'source /usr/local/share/bashcfg/common' >> /home/{{ username.stdout }}/.zshrc.local"
    - "echo 'source /usr/local/share/bashcfg/git_functions' >> /home/{{ username.stdout }}/.zshrc.local"
    when: not zshrclocal.stat.exists
    become: yes
    become_user: '{{ username.stdout }}'

