
  - name: Update cache
    apt:
      update_cache: yes

  - name: Install essential packages
    apt:
      state: latest
      pkg:
      - vim
      - curl
      - htop
      - git
      - mc
      - build-essential
      - net-tools
      - gettext
      - tree
      - tldr
