
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
      - python-docutils

 # Checks
 
 # Commands

  - name: Clone butt
    git:
     repo: 'https://github.com/InternetGuru/butt.git'
     dest: '/home/{{ username.stdout }}/butt'
  
  - name: Change ownership
    file:
      path: '/home/{{ username.stdout }}/butt'
      owner: '{{ username.stdout }}'
      group: '{{ username.stdout }}'
      state: directory
      recurse: yes
  
  - name: Make and install butt
    shell: ./configure && make && compiled/install
    args:
      chdir: '/home/{{ username.stdout }}/butt'

