
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
      - python3-docutils

 # Checks

 # Commands

  - name: Clone butt
    git:
     repo: 'https://github.com/InternetGuru/butt.git'
     dest: '/usr/local/src/butt'

  - name: Make and install butt
    shell: ./configure && make && compiled/install
    args:
      chdir: '/usr/local/src/butt'
