
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
      - python-docutils

 # Checks
 
 # Commands

  - name: Clone butt
    git:
     repo: 'https://github.com/InternetGuru/butt.git'
     dest: '/home/{{ username.stdout }}/butt'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Make and install butt
    shell: ./configure && make && compiled/install
    args:
      chdir: '/home/{{ username.stdout }}/butt'

