
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - git
      - python-docutils
    tags:
    - global

 # Checks

 # Commands

  - name: Clone butt
    git:
     repo: 'https://github.com/InternetGuru/butt.git'
     dest: '/usr/local/share/butt'
    tags:
    - global

  - name: Make and install butt
    shell: ./configure && make && compiled/install
    args:
      chdir: '/usr/local/share/butt'
    tags:
    - global
