
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - software-properties-common
    tags: global

 # Checks

 # Commands

  - name: Add diff-so-fancy repository
    shell:
      cmd: add-apt-repository ppa:aos1/diff-so-fancy
    tags: global

  - name: Install diff-so-fancy
    apt:
      pkg:
      - diff-so-fancy
    tags: global

  - name: Add git config
    community.general.git_config:
      name: core.pager
      scope: global
      value: diff-so-fancy | less --tabs=4 -RFX
    tags: user

  - name: Add git config
    community.general.git_config:
      name: interactive.diffFilter
      scope: global
      value: diff-so-fancy --patch
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.ui
      scope: global
      value: "true"
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff-highlight.oldNormal
      scope: global
      value: red bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff-highlight.oldHighlight
      scope: global
      value: red bold 52
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff-highlight.newNormal
      scope: global
      value: green bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff-highlight.newHighlight
      scope: global
      value: green bold 22
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.meta
      scope: global
      value: "11"
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.frag
      scope: global
      value: magenta bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.func
      scope: global
      value: 146 bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.commit
      scope: global
      value: yellow bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.old
      scope: global
      value: red bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.new
      scope: global
      value: green bold
    tags: user

  - name: Add git config colors
    community.general.git_config:
      name: color.diff.whitespace
      scope: global
      value: red reverse
    tags: user
