
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    tags:
    - global

 # Checks

 # Commands

  - name: Register lsb_release
    become: false
    local_action: command lsb_release -cs
    register: lsb_release
    tags:
    - global
  - name: Register uname_s
    become: false
    local_action: command uname -s
    tags:
    - global
    register: uname_s
  - name: Register uname_m
    become: false
    local_action: command uname -m
    register: uname_m
    tags:
    - global


  - name: Add docker gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
    - global

  - name: Add the Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout  }} stable
    tags:
    - global

  - name: Install docker
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      update_cache: yes
    tags:
    - global

  - name: Install docker-compose
    command: curl -L "https://github.com/docker/compose/releases/download/1.27.3/docker-compose-{{ uname_s.stdout }}-{{ uname_m.stdout  }}" -o /usr/local/bin/docker-compose
    tags:
    - global

  - name: Set docker-compose permissions
    command: chmod +x /usr/local/bin/docker-compose
    tags:
    - global
