
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

 # Checks

 # Commands

  - name: Add docker gpg key
    command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

  - name: Add the Docker APT repository
    command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

  - name: Install docker
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      update_cache: yes

  - name: Install docker-compose
    command: curl -L "https://github.com/docker/compose/releases/download/1.27.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  
  - name: Set docker-compose permissions
    command: chmod +x /usr/local/bin/docker-compose
