
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - gawk
      - git
      - python3-docutils

 # Checks

 # Commands

  - name: Clone flow
    git:
     repo: 'https://github.com/InternetGuru/flow.git'
     dest: '/usr/local/src/flow'

  - name: Make and install flow
    shell: ./configure && make && compiled/install
    args:
      chdir: '/usr/local/src/flow'
