
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - gawk
      - git
      - python3-docutils

 # Checks

 # Commands

  - name: Clone omgf
    git:
     repo: 'https://github.com/InternetGuru/omgf.git'
     dest: '/usr/local/src/omgf'

  - name: Make and install omgf
    shell: ./configure && make && compiled/install
    args:
      chdir: '/usr/local/src/omgf'
