
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - gawk
      - git
      - python-docutils

 # Checks
 
 # Commands

  - name: Clone omgf
    git:
     repo: 'https://github.com/InternetGuru/omgf.git'
     dest: '/home/{{ username.stdout }}/omgf'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Make and install omgf
    shell: ./configure && make && compiled/install
    args:
      chdir: '/home/{{ username.stdout }}/omgf'
