
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - libcanberra-gtk-module
      - libgconf-2-4
      - libatomic1

 # Checks

  - name: Check if pocorntime is installed
    stat:
      path: '/opt/popcorn-time'
    register: popcorntime

 # Commands

  - name: Create global directory
    file:
      path: /opt/popcorn-time
      state: directory

  - name: Download popcorntime 0.4.4
    unarchive:
      src: https://github.com/popcorn-time-ru/popcorn-desktop/releases/download/v0.4.5/Popcorn-Time-Ru-0.4.5-linux64.zip
      dest: /opt/popcorn-time
      remote_src: yes
    when: not popcorntime.stat.exists

  - name: Create a symbolic link
    file:
      src: /opt/popcorn-time/Popcorn-Time
      dest: /usr/bin/popcorn-time
      state: link

  - name: Install popcorntime.desktop
    ansible.builtin.copy:
      src: ../res/popcorntime.desktop
      dest: /usr/share/applications/

  - name: Download popcorntime icon
    get_url:
      url: https://goo.gl/wz8ifr
      dest: /opt/popcorn-time/popcorntime.png
