
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates

 # Checks

 # Commands

  - name: Add sublime gpg key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: Add sublime APT repository
    apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/

  - name: Install sublime
    apt:
      pkg: sublime-text
      update_cache: yes

  - name: Add sync settings plugin
    lineinfile:
      path: "/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"
      insertbefore: '"Package Control"'
      line: '"Sync Settings",'
    become: yes
    become_user: '{{ username.stdout }}'

  - name: Add sync settings gist_id
    shell: 'echo "{ \"gist_id\": \"abf3fa8890a04fd5dedb0dd20711f042\" }" > "/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/SyncSettings.sublime-setting"'
    become: yes
    become_user: '{{ username.stdout }}'
