
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - php-codesniffer
    tags: global

 # Checks

  - name: Check if sublime config exists
    stat:
      path: '/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings'
    check_mode: true
    changed_when: false
    register: sublime_config
    tags: user

  - name: Check if sublime sync config exists
    stat:
      path: '/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/SyncSettings.sublime-settings'
    check_mode: true
    changed_when: false
    register: sublime_sync_config
    tags: user

 # Commands

  - name: Force defaults (rm .bak)
    file:
      path: /home/{{ username.stdout }}/.config/sublime-text-3.bak
      state: absent
    tags:
      - force

  - name: Force defaults (move current config to .bak)
    command: mv /home/{{ username.stdout }}/.config/sublime-text-3 /home/{{ username.stdout }}/.config/sublime-text-3.bak
    args:
      removes: /home/{{ username.stdout }}/.config/sublime-text-3
    tags:
      - force

  - name: Force defaults (rm .bak)
    file:
      path: /home/{{ username.stdout }}/.cache/sublime-text-3.bak
      state: absent
    tags:
      - force

  - name: Force defaults (move current cache to .bak)
    command: mv /home/{{ username.stdout }}/.cache/sublime-text-3 /home/{{ username.stdout }}/.cache/sublime-text-3.bak
    args:
      removes: /home/{{ username.stdout }}/.cache/sublime-text-3
    tags:
      - force

  - name: Add Sublime gpg key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present
    tags: global

  - name: Add the Sublime APT repository
    apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/
    tags: global

  - name: Install Sublime
    apt:
      pkg:
      - sublime-text
    tags: global

  - name: Add Sync Settings plugin
    lineinfile:
      path: '/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings'
      line: '{"installed_packages": ["Package Control", "Sync Settings"]}'
      create: yes
    when: not sublime_config.stat.exists
    become: yes
    become_user: '{{ username.stdout }}'
    tags: user

  - name: Add Sync Settings gist_id
    lineinfile:
      path: '/home/{{ username.stdout }}/.config/sublime-text-3/Packages/User/SyncSettings.sublime-settings'
      line: '{ "gist_id": "abf3fa8890a04fd5dedb0dd20711f042" }'
      create: yes
    when: not sublime_sync_config.stat.exists
    become: yes
    become_user: '{{ username.stdout }}'
    tags: user

  - name: Install IGCMS Code Sniffer ruleset
    copy:
      src: '../res/ruleset.xml'
      dest: '/usr/share/php/PHP/CodeSniffer/src/Standards/IGCMS/'
    tags: global
