
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - curl
      - fonts-firacode
    tags: global

 # Checks

 # Commands

  - name: Download starship prompt
    get_url:
      url: https://starship.rs/install.sh
      dest: /tmp/starship.sh
      mode: 0755
    tags: global

  - name: Install starship prompt
    shell: /tmp/starship.sh --yes
    args:
      warn: false
    tags: global

  - name: Set starship prompt as default
    lineinfile:
      path: '/home/{{ username.stdout }}/.bashrc'
      line: 'eval "$(starship init bash)"'
      create: yes
      state: present
    become: yes
    become_user: '{{ username.stdout }}'
    tags: user

  - name: Copy starship.toml iff not exists
    copy:
      src: '../res/starship.toml'
      dest: '/home/{{ username.stdout }}/.config/'
      force: no
    tags: user
