
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - fish
      - curl
      - fonts-firacode
    tags:
    - global

 # Checks

 # Commands

  - name: Set Fish as default shell
    user:
      name: '{{ username.stdout }}'
      shell: /usr/bin/fish
    tags:
    - skip

  - name: Disable fish greeting
    lineinfile:
      path: '/home/{{ username.stdout }}/.config/fish/config.fish'
      line: 'set fish_greeting'
      create: yes
      state: present
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
    - user

  - name: Install starship prompt
    shell: curl -fsSL https://starship.rs/install.sh | bash -s -- --yes
    args:
      warn: false
    tags:
    - global

  - name: Set starship prompt as default
    lineinfile:
      path: '/home/{{ username.stdout }}/.config/fish/config.fish'
      line: 'starship init fish | source'
      create: yes
      state: present
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
    - user

  - name: Copy starship.toml iff not exists
    copy:
      src: '../res/starship.toml'
      dest: '/home/{{ username.stdout }}/.config/'
      force: no
    tags:
    - user
