  - name: Automatic timezone
    community.general.dconf:
      key: '/org/gnome/desktop/datetime/automatic-timezone'
      value: 'true'

  - name: Set en, cz input sources
    community.general.dconf:
      key: '/org/gnome/desktop/input-sources/sources'
      value: "[('xkb', 'us'), ('xkb', 'cz')]"

  - name: Keyboard dely
    community.general.dconf:
      key: '/org/gnome/desktop/peripherals/keyboard/delay'
      value: 'uint32 263'

  - name: Activate numlock
    community.general.dconf:
      key: '/org/gnome/desktop/peripherals/keyboard/numlock-state'
      value: 'true'

  - name: Keboard repeat interval
    community.general.dconf:
      key: '/org/gnome/desktop/peripherals/keyboard/repeat-interval'
      value: 'uint32 34'

  - name: Lock screen after 15 min
    community.general.dconf:
      key: '/org/gnome/desktop/session/idle-delay'
      value: 'uint32 900'

  - name: Disable dynamic workspaces
    community.general.dconf:
      key: '/org/gnome/mutter/dynamic-workspaces'
      value: 'false'

  - name: Enable numlock
    community.general.dconf:
      key: '/org/gnome/settings-daemon/peripherals/keyboard/numlock-state'
      value: "'on'"

  - name: Enable night-light
    community.general.dconf:
      key: '/org/gnome/settings-daemon/plugins/color/night-light-enabled'
      value: 'true'

  - name: Enable night-light automatic shedule
    community.general.dconf:
      key: '/org/gnome/settings-daemon/plugins/color/night-light-schedule-automatic'
      value: 'true'

  - name: Set night-light temperature
    community.general.dconf:
      key: '/org/gnome/settings-daemon/plugins/color/night-light-temperature'
      value: 'uint32 2700'

  - name: Disable screen dim
    community.general.dconf:
      key: '/org/gnome/settings-daemon/plugins/power/idle-dim'
      value: 'false'

  - name: Disable automatic sleep
    community.general.dconf:
      key: '/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type'
      value: "'nothing'"

  - name: Enable extensions
    community.general.dconf:
      key: '/org/gnome/shell/enabled-extensions'
      value: "['disable-screenshield@lgpasquale.com', 'dash-to-panel@jderose9.github.com', 'clock-override@gnomeshell.kryogenix.org']"

  - name: Set favorite apps
    community.general.dconf:
      key: '/org/gnome/shell/favorite-apps'
      value: "['google-chrome.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'code.desktop', 'slack.desktop']"

  - name: Clock override format
    community.general.dconf:
      key: '/org/gnome/shell/extensions/clock_override/override-string'
      value: "'%a %e. %b %H:%M'"

  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/animate-app-switch'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/animate-window-launch'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/check-update'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-1'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-2'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-3'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-4'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-1'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-2'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-3'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-color-unfocused-4'
      value: "'#5294e2'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-size'
      value: '5'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-style-focused'
      value: "'METRO'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/dot-style-unfocused'
      value: "'DOTS'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/focus-highlight-color'
      value: "'#eeeeee'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/force-check-update'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/group-apps'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/hot-keys'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/hotkeys-overlay-combo'
      value: "'TEMPORARILY'"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/intellihide'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/leftbox-padding'
      value: '-1'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/multi-monitors'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-activities-button'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-appmenu'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-apps-icon-file'
      value: "''"
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-favorites'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-show-apps-button'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-showdesktop-button'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/show-window-previews'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/status-icon-padding'
      value: '-1'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/taskbar-locked'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/trans-panel-opacity'
      value: '0.25'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-bg'
      value: 'false'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-gradient'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/trans-use-custom-opacity'
      value: 'true'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/tray-padding'
      value: '-1'
  - name: Dash-to-panel settings
    community.general.dconf:
      key: '/org/gnome/shell/extensions/dash-to-panel/window-preview-title-font-color'
      value: "'#dddddd'"
  
  - name: Set filechooser sort
    community.general.dconf:
      key: '/org/gtk/settings/file-chooser/sort-column'
      value: "'modified'"

  - name: Disable system sounds
    community.general.dconf:
      key: '/org/gnome/desktop/sound/event-sounds'
      value: 'false'
