
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - ufw
    tags:
    - global

 # Commands

  - name: Deny all and enable UFW
    ufw:
      state: enabled
      policy: deny
    tags:
    - global

  - name: Rate limiting ssh connection (6 or more in the last 30 sec)
    ufw:
      rule: limit
      port: ssh
      proto: tcp
    tags:
    - global

  - name: Default tcp allow in
    ufw:
      rule: allow
      proto: tcp
      direction: in
      port: '{{ item }}'
    loop:
    - '22'
    - '80'
    - '443'
    - '5000:5100'
    - '445'
    - '139'
    - '5900'
    tags:
    - global

  - name: Default allow in
    ufw:
      rule: allow
      direction: in
      port: '{{ item }}'
    loop:
    - '35729'
    - '7890'
    tags:
    - global

  - name: Default tcp allow out
    ufw:
      rule: allow
      proto: tcp
      direction: out
      port: '{{ item }}'
    loop:
    - '22'
    - '80'
    - '443'
    - '873'
    tags:
    - global

  - name: Default allow out
    ufw:
      rule: allow
      direction: out
      port: '{{ item }}'
    loop:
    - '53'
    - '25'
    - '995'
    tags:
    - global
