
 # Dependency


 # Checks

  - name: Check if ~/.config/autostart/variety.desktop exists
    stat:
      path: '/home/{{ username.stdout }}/.config/autostart/variety.desktop'
    register: varietyautostart

 # Commands

  - name: Create /home/{{ username.stdout }}/.config/autostart
    file:
      path: '/home/{{ username.stdout }}/.config/autostart'
      state: directory

  - name: Copy variety settings iff not exists
    copy:
      src: '../res/variety/'
      dest: '/home/{{ username.stdout }}/.config/variety/'
      force: no

  - name: Create variety autostart iff not exists
    shell: 'printf "$(cat "{{ playbook_dir }}/res/variety.desktop")" "{{ username.stdout }}" > "/home/{{ username.stdout }}/.config/autostart/variety.desktop"'
    when: not varietyautostart.stat.exists
