
 # Dependency

  - name: Install dependencies
    apt:
      pkg:
      - curl
      - vim
    tags:
    - global

 # Checks

  - name: Check if ~/vimrc exists
    stat:
      path: '/home/{{ username.stdout }}/vimrc'
    register: vimrc
    tags:
    - user

 # Commands

  - name: Clone vimrc repo
    git:
     repo: 'https://github.com/petrzpav/vimrc'
     dest: '/home/{{ username.stdout }}/vimrc'
    become: yes
    become_user: '{{ username.stdout }}'
    tags:
    - user

  - name: Add global vimrc link
    file:
      src: '/home/{{ username.stdout }}/vimrc/vimrc'
      dest: '/etc/vim/vimrc'
      state: link
      force: yes
    when: not vimrc.stat.exists
    tags:
    - user

  - name: Add global vimrc.local link
    file:
      src: '/home/{{ username.stdout }}/vimrc/vimrc.local'
      dest: '/etc/vim/vimrc.local'
      state: link
      force: yes
    when: not vimrc.stat.exists
    tags:
    - user

