  - name: Add Microsoft GPG key
    ansible.builtin.apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add Visual Studio Code repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
      state: present
      filename: vscode

  - name: Install Visual Studio Code
    ansible.builtin.apt:
      name: code
      state: present
      update_cache: yes
